[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 1
solc_version = "0.8.7"
evm_version = "london"
optimizer_details = { jumpdestRemover = true, orderLiterals = true, deduplicate = true, cse = true, constantOptimizer = true, yul = true, yulDetails = { stackAllocation = true, optimizerSteps = "dhfoDgvulfnTUtnIf" } }
memory_limit = 34359738368
ffi = true
force = true

# Additional settings
sparse_mode = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"